version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: devops_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r00t16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/data/posgresql/data
      - ./init-db:/docker-entrypoint-initdb.d 

  web:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: devops_app
      DB_USER: postgres
      DB_PASSWORD: r00t16
      DB_PORT: 5432

volumes:
  postgres_data:
