name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for app to be ready
        run: |
          for i in {1..10};do
            if curl -f http://localhost:8000/health; then
              echo "App is ready"
              exit 0
            fi
            echo "Waiting for app ..."
            sleep 3
          done
          echo "App failed to start"
          exit 1  

      - name: Stop containers
        if: always()
        run: docker compose down

      - name: Log into Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}             
  
      - name: Build Docker Image
        run: |
          docker build \
            -t qu35t16/scaffold-task-tracker:${{ github.sha }} \
            -t qu35t16/scaffold-task-tracker:latest .

      - name: Push Docker image
        run: |
          docker push qu35t16/scaffold-task-tracker:${{ github.sha }}
          docker push qu35t16/scaffold-task-tracker:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
    
      - name: Build artifcats
        run: |
          echo "Build ID: ${{ github.sha }}" > build-info.txt
          echo "Build time: $(date)" >> builf-info.txt
 
      - name: Upload artifact to S3
        run: |
          aws s3 cp build-info.txt s3://${{ secrets.S3_BUCKET_NAME }}/builds/${{ github.sha }}.txt
 
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd scaffold-task-tracker
            git pull
            docker compose down
            docker compose pull
            docker compose up -d
